#!/bin/bash

PVCPATH=~/.pvc
PVCLIB=$PVCPATH/lib
PVCSRC=$PVCPATH/src


PVC_NOT_INSTALLED_MSG () {
    echo "Python version ${1} is not installed."
}

PVC_ALREADY_INSTALLED_MSG () {
    echo "Python version ${1} is already installed."
    echo "use \`pvc uninstall ${1}\` to uninstall."
}

PVC_INVALID_VERSION_MSG () {
    echo "${1} is not a valid python version."
}

PVC_PYTHON_VERSION_NOT_INSTALLED () {
    echo "${1} is not installed."
}


# Check if the given argument is a valid python version
pvc_is_valid_python_version () {
    if [[ ! -z $1 ]]; then
        if [[ $1 =~ ^[0-9].[0-9].[0-9]$ ]]; then
            return 0
        fi
    fi
    PVC_INVALID_VERSION_MSG $1
    return 1
}

pvc_python_version_is_installed () {
  if [[ ! -z $1 ]]; then
    if pvc_is_valid_python_version $1; then
      if [[ -d $PVCPATH/$1 ]]; then
        return 0
      fi
    fi
  fi
  PVC_PYTHON_VERSION_NOT_INSTALLED $1
  return 1
}

# Unicode symbols
snake_emoji="\xF0\x9F\x90\x8D "
check_emoji="✓"
fail_emoji="\033[0;31m\xE2\x9C\x96\033[0m "


# Check if the specified python version is installed
is_installed () {
    if [[ -d $PVCPATH/$1 ]]; then
        return 0
    fi
    return 1
}

# Check if the specified python version can be installed
can_install () {
    if pvc_is_valid_python_version $1; then
        if is_installed $1; then
            PVC_ALREADY_INSTALLED_MSG $1
            return 1
        fi
    else
        PVC_INVALID_VERSION_MSG $1
        return 1
    fi
    return 0

}

# Install the specified python version
pvc_install_python_version () {
    PWD=$(pwd)
    mkdir -p $PVCSRC
    cd $PVCSRC
    curl -Lo Python-${1}.tgz \
        http://www.python.org/ftp/python/${1}/Python-${1}.tgz


    if ! cat $PVCSRC/Python-${1}.tgz | grep -q "404 Not Found"; then
        echo "${check_emoji} Downloaded Python-${1}.tgz"
        tar -zxvf $PVCSRC/Python-${1}.tgz
        cd Python-${1}
        ./configure --prefix=$PVCPATH/${1} --with-ssl
        make
        make install
        echo "${check_emoji} Installed Python-${1} to ${PVCPATH}/${1}"
        cd ..
        pvc default use $1
        curl -Lo setuptools.zip https://pypi.python.org/packages/source/s/setuptools/setuptools-20.0.zip#md5=956e34a45b83a6452fa952d24240f377
        unzip setuptools.zip -d setuptools
        cd setuptools/setuptools-20.0
        python setup.py install --prefix=$PVCPATH/${1}
        cd $PWD
        #rm -rf $PVCSRC
        #echo "${check_emoji} Cleaned up src folder."
    else
        echo "${fail_emoji} Python-${1} not found. Is it a real version?"
    fi
}

# uninstall the specified python version
pvc_uninstall_python_version () {
    if [[ -d $PVCPATH/$1 ]]; then
        rm -rf $PVCPATH/${1}
        echo "Uninstalled ${1}"
    else
        PVC_NOT_INSTALLED_MSG $1
    fi
}

pvc () {
  case $1 in

    # 01 - The Install Command
    install)
      if can_install $2; then
        pvc_install_python_version $2
      fi
    ;;

    # 02 - The Uninstall Command
    uninstall)
      if pvc_is_valid_python_version $2; then
        pvc_uninstall_python_version $2
      fi
    ;;

    # 03 - The Default Command
    default)
      case $2 in
        use)
          if pvc_python_version_is_installed $3; then
            echo "export PATH=${PVCPATH}/${3}/bin:\$PATH" > $PVCPATH/.profile
            echo "export PYTHONPATH=${PVCPATH}/${2}/lib/python${3}/site-packages" >> $PVCPATH/.profile
            echo "${3}" > $PVCPATH/p.vc
            . $PVCPATH/.profile
          fi
        ;;
        show)
          echo "Using Python version $(cat $PVCPATH/p.vc)"
        ;;
        *)
          echo "Usage: pvc default [use|show]"
        ;;
      esac
    ;;

    # 04 - The Autoclean Command
    autoclean)
      rm -rvf $PVCPATH/src/*
      echo "${check_emoji} Done cleaning!"
    ;;
    esac
}
